### PR TITLE
- Fixed work with Android Studio 4.1.1

### PR DESCRIPTION
**Pull request by GeniusRUS**

### CODE REVIEW

**Comment by timtsj** [comment]
@galex ping

**Comment by SlavisDEV** [comment]
@galex ping

**Review by galex — COMMENTED** [review]
Thank you but this PR doesn't upgrade the IntelliJ API version for which the plugin has been written and thus need to adjust to.

**Comment by galex** [comment]
I've updated the plugin to 2020.3 :)

**Pull request closed without merging**
